/**
 * Names for op-0x01 call ids, taken from the handlers registered in the game's function table at
 * 0x09CE73F4 (FUN_0889671c, FUN_08890ee4, FUN_0889b880, FUN_08896678). Names are descriptive: the
 * original source names are not in the executable, except scr_LoadSprite / scr_LoadAnm.
 * `args` lists arguments in push order (i = int, f = float, s = string, L = label, & = reference).
 */
export interface CasFunc {
  name: string
  args?: string
}

const ops = (ids: number[], names: string[], args: string): Record<number, CasFunc> =>
  Object.fromEntries(ids.map((id, i) => [id, { name: names[i], args }]))

export const CAS_FUNCS: Record<number, CasFunc> = {
  0x00: { name: 'nop' },
  ...ops([0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11], ['+', '-', '*', '/', '%', '&', '|', '^'], 'a, b'),
  ...ops([0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19], ['||', '&&', '==', '!=', '<', '>', '<=', '>='], 'a, b'),
  0x1a: { name: 'neg', args: 'a' },
  0x1b: { name: '!', args: 'a' },
  ...ops([0x1e, 0x1f, 0x20, 0x21, 0x22, 0x23], ['=', '+=', '-=', '*=', '/=', '%='], '&a, b'),

  0x46: { name: 'goto', args: 'L' },
  0x47: { name: 'if_true_goto', args: 'cond, L' },
  0x48: { name: 'if_false_goto', args: 'cond, L' },
  0x49: { name: 'gosub', args: 'L' },
  0x4a: { name: 'if_true_gosub (broken)', args: 'cond, L' },
  0x4b: { name: 'if_false_gosub (broken)', args: 'cond, L' },
  0x4c: { name: 'return', args: 'v' },
  0x4d: { name: 'if_true_return (broken)', args: 'cond' },
  0x4e: { name: 'if_false_return (broken)', args: 'cond' },

  0x5f: { name: 'local_int', args: 'i idx' },
  0x60: { name: 'local_float', args: 'i idx' },
  0x63: { name: 'copy_locals', args: 'i dst, i src' },
  0x64: { name: 'wait_frame', args: 'i' },
  0x65: { name: 'pop' },
  0x66: { name: 'exit' },
  0x67: { name: 'stub', args: 'i' },
  0x68: { name: 'kill_script', args: 'i slot' },
  0x69: { name: 'pause_others', args: 'i' },
  0x6a: { name: 'resume_all', args: 'i' },
  0x6b: { name: 'user_error', args: 'i' },
  0x6c: { name: 'error', args: 's message' },
  0x6d: { name: 'call_func', args: 'L, args…' },
  0x6e: { name: 'set_entry', args: 'i n, L' },
  0x6f: { name: 'disable_entry', args: 'i n' },
  0x70: { name: 'start_thread', args: 'i thread, L' },
  0x71: { name: 'stop_thread', args: 'i thread' },
  0x72: { name: 'thread_running', args: 'i thread' },
  0x73: { name: 'thread_id', args: 'i' },
  0x74: { name: 'trigger_entry', args: 'i slot, i n' },
  0x75: { name: 'arg_count' },
  0x76: { name: 'arg_int', args: 'i k' },
  0x77: { name: 'arg_float', args: 'i k' },
  0x78: { name: 'script_slot' },
  0x79: { name: 'arg_str', args: 'i k' },
  0x7b: { name: 'scr_LoadData', args: 'dataSlot, archive, entry, member, allocSize' },
  0x7c: { name: 'free_data', args: 'slot' },
  0x7d: { name: 'start_script', args: 'scriptSlot, dataSlot' },
  0x80: { name: 'print_num', args: 'n' },
  0x82: { name: 'print_str', args: 's' },
  0x8c: { name: 'ftoi', args: 'f' },
  0x8d: { name: 'itof', args: 'i' },
  0x8e: { name: 'rand', args: 'i n' },
  0x90: { name: 'strcmp', args: 's a, s b, i n' },

  ...ops([0xc8, 0xc9, 0xca, 0xcb, 0xcc, 0xcd], ['sin', 'cos', 'tan', 'asin', 'acos', 'atan'], 'f'),
  0xd0: { name: 'deg2rad', args: 'f' },
  0xd1: { name: 'rad2deg', args: 'f' },
  0xd2: { name: 'pow', args: 'f a, f b' },
  0xd3: { name: 'ipow', args: 'i a, i b' },
  0xd7: { name: 'ln', args: 'f' },
  0xd8: { name: 'log10', args: 'f' },
  0xd9: { name: 'ilog10', args: 'i' },
  0xda: { name: 'log2', args: 'f' },
  0xdb: { name: 'bits_needed', args: 'i' },
  0xdc: { name: 'max', args: 'i, i' },
  0xdd: { name: 'min', args: 'i, i' },
  0xde: { name: 'abs', args: 'i' },
  0xe1: { name: 'fmax', args: 'f, f' },
  0xe2: { name: 'fmin (returns max)', args: 'f, f' },
  0xe3: { name: 'fabs', args: 'f' },
  0xe6: { name: 'sqrt', args: 'f' },
  0xe7: { name: 'length3', args: 'f x, f y, f z' },
  0xe8: { name: 'distance3', args: '6 × f' },
  0xeb: { name: 'isqrt', args: 'i' },
  0xec: { name: 'ilength3', args: 'i, i, i' },
  0xed: { name: 'idistance3', args: '6 × i' },

  // Effect library (scrRegisterEffectFuncs). Positions are (x, d, h): world = (x, -h, -d) for 3D
  // objects. Tween "speed" is units (or radians) per second, not a duration.
  0x180: { name: 'cam_add_pos', args: 'cam, x, d, h' },
  0x181: { name: 'cam_set_pos', args: 'cam, x, d, h' },
  0x182: { name: 'cam_get_pos', args: 'cam, &x, &d, &h' },
  0x184: { name: 'cam_set_rot', args: 'cam, f rx, f ry, f rz' },
  0x186: { name: 'scr_LoadSprite', args: 'obj, archive, entry, member, flags' },
  0x187: { name: 'scr_LoadAnm', args: 'obj, archive, entry, member, flags' },
  0x188: { name: 'obj_is_loading', args: 'obj' },
  0x18b: { name: 'cam_viewport', args: 'cam, x, y, w, h' },
  0x18c: { name: 'cam_projection', args: 'cam, i focal, f sx, f sy' },
  0x18d: { name: 'cam_config', args: 'cam, rate, s0, s1, s2' },
  0x191: { name: 'obj_set_state', args: 'obj, op' },
  0x193: { name: 'obj_release', args: 'obj' },
  0x194: { name: 'obj_clone', args: 'dst, src' },
  0x195: { name: 'obj_free', args: 'obj' },
  0x196: { name: 'obj_set_camera', args: 'obj, cam' },
  0x197: { name: 'obj_set_parent', args: 'obj, parent' },
  0x19a: { name: 'obj_add_pos', args: 'obj, x, d, h' },
  0x19b: { name: 'obj_add_rot', args: 'obj, f rx, f ry, f rz' },
  0x19c: { name: 'obj_add_scale', args: 'obj, f sx, f sy' },
  0x19d: { name: 'obj_set_pos', args: 'obj, x, d, h' },
  0x19e: { name: 'obj_set_scale', args: 'obj, f sx, f sy' },
  0x19f: { name: 'obj_set_rot', args: 'obj, f rx, f ry, f rz' },
  0x1a0: { name: 'obj_set_shadow_offset', args: 'obj, 0, value' },
  0x1a1: { name: 'obj_set_rgba', args: 'obj, r, g, b, a' },
  0x1a2: { name: 'obj_set_blend', args: 'obj, mode' },
  0x1a3: { name: 'obj_add_pos_f', args: 'obj, f x, f d, f h' },
  0x1a4: { name: 'tween_pos_rel', args: 'obj, dx, dd, dh, speed' },
  0x1a5: { name: 'tween_pos_arc', args: 'obj, x, d, h, speed, height' },
  0x1a7: { name: 'tween_pos', args: 'obj, x, d, h, speed' },
  0x1a8: { name: 'tween_scale', args: 'obj, f sx, f sy, f speed' },
  0x1a9: { name: 'tween_rot', args: 'obj, f rx, f ry, f rz, f speed' },
  0x1ab: { name: 'tween_rgba', args: 'obj, r, g, b, a, speed' },
  0x1ac: { name: 'obj_tween_flags', args: 'obj' },
  0x1ad: { name: 'set_global_tint', args: 'r, g, b, speed' },
  0x1b1: { name: 'obj_get_pos', args: 'obj, &x, &d, &h' },
  0x1b2: { name: 'obj_get_scale', args: 'obj, &sx, &sy' },
  0x1b3: { name: 'obj_get_rot', args: 'obj, &rx, &ry, &rz' },
  0x1b5: { name: 'obj_get_rgba', args: 'obj, &r, &g, &b, &a' },
  0x1b6: { name: 'cam_world_to_screen', args: 'cam, &x, &d, &h' },
  0x1b8: { name: 'sprite_anchor', args: 'obj, flags' },
  0x1b9: { name: 'sprite_pivot', args: 'obj, px, py' },
  0x1ba: { name: 'sprite_src_rect', args: 'obj, u, v, w, h' },
  0x1bb: { name: 'sprite_reset_offset', args: 'obj' },
  0x1c0: { name: 'poly_create', args: 'obj, pattern, srcObj' },
  0x1c1: { name: 'poly_params', args: 'obj, radiusA, radiusB, height, f spread, spin' },
  0x1c2: { name: 'anim_switch', args: 'obj, anim' },
  0x1c3: { name: 'anim_get_current', args: 'obj' },
  0x1c4: { name: 'anim_query', args: 'obj, what' },
  0x1c5: { name: 'anim_marker_step', args: 'obj, marker' },
  0x1c6: { name: 'anim_set_time', args: 'obj, frame' },
  0x1c7: { name: 'anim_set_step', args: 'obj, step' },
  0x1c8: { name: 'anim_get_time', args: 'obj' },
  0x1c9: { name: 'anim_get_step', args: 'obj' },
  0x1ca: { name: 'anim_play', args: 'obj' },
  0x1cb: { name: 'anim_stop', args: 'obj' },

  // Game functions (scrRegisterGameFuncs). Several are stubs left in the engine; the item, party and date
  // functions work on an unused RPG-engine block that the game never fills (docs/formats/save-menus.md).
  0x100: { name: 'game_set_flag', args: 'flag, val' },
  0x101: { name: 'game_get_flag', args: 'flag' },
  0x102: { name: 'game_set_var', args: 'idx, v' },
  0x103: { name: 'game_get_var', args: 'idx' },
  0x104: { name: 'game_set_var_f', args: 'idx, f v' },
  0x105: { name: 'game_get_var_f', args: 'idx' },
  0x106: { name: 'game_get_seq_counter' },
  0x107: { name: 'game_seq_lock' },
  0x108: { name: 'game_seq_unlock' },
  0x109: { name: 'game_set_var_bit', args: 'idx, bit, val' },
  0x10a: { name: 'game_get_var_bit', args: 'idx, bit' },
  0x10e: { name: 'game_get_cur_party_slot' },
  0x10f: { name: 'game_get_year_month', args: '&year, &month' },
  0x116: { name: 'identity', args: 'x' },
  0x11b: { name: 'game_chara_flag', args: 'charaIdx, mode' },
  0x127: { name: 'game_party_get', args: 'field, slot, bit, &out' },
  0x128: { name: 'game_party_set', args: 'field, slot, bit, val' },
  0x12c: { name: 'game_add_item', args: 'item, n' },
  0x12d: { name: 'game_sub_item', args: 'item, n' },
  0x12e: { name: 'game_get_item', args: 'item' },
  0x12f: { name: 'str_buf_set', args: 'buf, s text' },
  0x131: { name: 'win_open_msg', args: 'win, f x, f y, f w, f h, s text, faceKey, flags' },
  0x132: { name: 'win_open_menu', args: 'win, f x, f y, glyphW, glyphH, s text' },
  0x133: { name: 'win_close_top' },
  0x134: { name: 'win_close_bottom' },
  0x135: { name: 'win_close', args: 'win' },
  0x136: { name: 'win_close_all', args: 'win' },
  0x137: { name: 'win_bring_to_front', args: 'win' },
  0x138: { name: 'win_poll_decide', args: 'win' },
  0x139: { name: 'win_get_cursor', args: 'win' },
  0x13a: { name: 'win_set_pos', args: 'win, f x, f y' },
  0x13b: { name: 'win_set_size', args: 'win, f w, f h' },
  0x13c: { name: 'win_set_color', args: 'win, f v' },
  0x13d: { name: 'win_set_cursor', args: 'win, f v' },
  0x13e: { name: 'win_set_text', args: 'win, s text, typeMode, color' },
  0x13f: { name: 'win_show', args: 'win' },
  0x140: { name: 'win_update_input', args: 'win' },
  0x141: { name: 'win_set_depth', args: 'win, depth' },
  0x144: { name: 'win_open_msg_buf', args: 'win, f x, f y, f w, f h, strBuf, faceKey, flags' },
  0x145: { name: 'bgm_play', args: 'slot, track' },
  0x146: { name: 'bgm_restart', args: 'slot' },
  0x147: { name: 'bgm_stop', args: 'slot' },
  0x148: { name: 'bgm_add_volume', args: 'slot, delta' }, // bookkeeping only, never applied
  0x149: { name: 'bgm_play_fade_in', args: 'slot, track, unusedFade' },
  0x14a: { name: 'bgm_fade_out', args: 'slot, unusedSpeed' },
  0x14b: { name: 'bgm_fade_out_nz', args: 'slot, enable' },
  0x14c: { name: 'se_play', args: 'seId, unused' },
  0x14d: { name: 'se_stop', args: 'unused' },
  0x14e: { name: 'snd_stub', args: 'a, b' },
  0x14f: { name: 'voice_play', args: 'vagId' },
  0x150: { name: 'voice_stop' },
  0x151: { name: 'voice_is_idle' },
  0x152: { name: 'stream_play', args: 'track' },
  0x153: { name: 'stream_stop' },
  0x154: { name: 'snd_stub', args: 'a, mode' },
  0x155: { name: 'snd_stub', args: 'a, b, c, d' },
  0x156: { name: 'se_play_ex', args: 'seId, a, b, c, d' },
  0x157: { name: 'se_stop_all' },
  0x158: { name: 'stream_is_playing' },
  0x172: { name: 'arr_fill_int', args: '&arr, val, n' },
  0x173: { name: 'arr_fill_float', args: '&arr, val, n' },
  0x174: { name: 'arr_clear_int', args: '&arr, n' },
  0x175: { name: 'arr_clear_float', args: '&arr, n' },
  0x176: { name: 'arr_copy_int', args: '&dst, &src, n' },
  0x177: { name: 'arr_copy_float', args: '&dst, &src, n' },
  0x178: { name: 'point_in_rect', args: 'f x, f y, f x0, f y0, f x1, f y1' },
  0x179: { name: 'point_in_circle', args: 'f x, f y, f cx, f cy, f r' },
  0x17a: { name: 'approach_down', args: '&v, target, step' },
  0x17b: { name: 'approach_up', args: '&v, target, step' },
  0x17e: { name: 'rand_jitter_2d', args: '&x, &y, f unused' },

  // Battle / map state (scrRegisterSysFuncs).
  0x320: { name: 'battle_get_both_pos', args: '&lx, &ly, &lz, &rx, &ry, &rz' },
  0x321: { name: 'battle_get_attacker_side', args: '&out' },
  0x322: { name: 'battle_get_defender_side', args: '&out' },
  0x323: { name: 'battle_get_side_pos', args: 'side, &x, &y, &z' },
  0x384: { name: 'result_get_winner', args: '&winnerSide, &loserChara' },
  0x385: { name: 'map_get_cam_pos', args: '&x, &y, &z' },
  0x386: { name: 'map_get_cam_rot', args: '&rx, &ry, &rz' },
  0x387: { name: 'stub', args: 'i' },
  0x388: { name: 'map_place_cur_unit' },
  0x389: { name: 'map_remove_cur_unit' },
}

export function casFuncName(id: number): string {
  return CAS_FUNCS[id]?.name ?? `fn_${id.toString(16).padStart(3, '0')}`
}
